config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'student_login', to: 'sessions#new_student'
  get 'professor_login', to: 'sessions#new_professor'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'

  resources :holdprojects

  resources :takings

  resources :courses do 
    member do
      post 'create_groups'
      patch 'toggle_voting'
    end
  end
  
  resources :professors

  resources :students do
    member do
      get 'add_course'
      post 'search_course'
      delete 'drop_course'
    end
  end


  resources :professors do
    member do
      get 'add_course'
      post 'create_course'
    end
  end

  resources :account_activations, only: [:edit]

  resources :preferences 

  resources :groups do
    member do
      patch :move
      patch :vote
    end 
  end 


  root 'pages#home'
end

app/models/student.rb
class Student < ApplicationRecord
    attr_accessor :activation_token
    has_many :takings
    has_many :courses, through: :takings
    has_many :groups, through: :takings
    has_many :preferences
    accepts_nested_attributes_for :courses, allow_destroy: true
    def full_name
        "#{firstname + " " + lastname}"
    end

    before_save { self.email = email.downcase }
    before_create :create_activation_digest

    validates :firstname,  presence: true, length: { maximum: 50 }
    validates :lastname,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, 
            format: { with: VALID_EMAIL_REGEX }, 
            uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    validates :email, uniqueness: true
    def Student.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def full_name
        firstname.to_s + " " + lastname.to_s
    end

    # Activates an account.
    def activate
        update_attribute(:activated, true)
    end

    # Sends activation email.
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

    # Returns a random token.
    def Student.new_token
        SecureRandom.urlsafe_base64
    end

    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    private

        # Creates and assigns the activation token and digest.
        def create_activation_digest
            self.activation_token  = Student.new_token
            self.activation_digest = Student.digest(activation_token)
        end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :add_course, :drop_course, :search_course]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @courses = @student.courses
    @groups = @student.groups
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    @courses = @student.courses.all
  end

  #GET /students/1/add_course
  def add_course
    @student_id = params[:id]
  end

  #POST /students/1/search_course
  def search_course
    registrar = EnrollmentManager::Registrar.new
    registrar_notice = registrar.enroll_in_course(@student.id, params[:pin])
    redirect_to @student, notice: registrar_notice 
  end

  #DELETE /students/1/drop_course?course=1
  def drop_course
    registrar = EnrollmentManager::Registrar.new
    registrar.drop_course(params[:student_id], params[:course_id])
    respond_to do |format|
      format.html { redirect_to @student, notice: 'Class was dropped.' }
      format.json { head :no_content }
    end
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    respond_to do |format|
      @student.activated = true
      if @student.save
        # @student.activated = true
        log_in(@student, "student")
        
        format.html { redirect_to root_url}
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:firstname, :password, :password_confirmation, :lastname, :email, :Vfirst, :Vsecond, :Vthird, courses_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_add_form.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_with(url: search_course_student_path, method: "post", class: "form-inline") do |f|%>

            <%= f.text_field :pin, placeholder: "Enter Course Pin"%>
            <%= submit_tag("Add", class: "add-course-button") %>
           
        <% end %>
    </div>
</div>

app/views/students/_course.html.erb
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

<div class="container course-column-box">
    <div class='row course-name-row'>
        <div id="course-name"><%= link_to course.name, course, class:'btn course-name-button' %></div>
    </div>
    
    <% group = findGroup(@student, course) %>
    <% if group.nil? %>
        <div class='not-assigned-text'>
            <h6>You have not been assigned to a team</h6>
        </div>
    <% else %>
        <div class='profile-group-row' >
            <p class='profile-group-pre'>You are currently on team:    </p>
            <h5 class='profile-group-name'><%= group['project_name'] %></h5>
            <p class="group-icon"><a href="#">show members</a></p>
            
        </div>

        <div>
            <% group_members = group.students%>
            <div class = "wrapper overflow group-container">
                <table class = "table table-hover table-sm member-table" id='member-table'>
                    <thead>
                        <tr>
                            <th style='border-top: 0'>Name</th>
                            <th style='border-top: 0'>Email</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% group_members.each do |stu| %>
                        <tr>
                            <td><%= stu.firstname + " " + stu.lastname%>
                            <td><%= stu.email%>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
        
    <% end %>
    <div class='row course-drop-row'>
        <div id="course-drop-button">
        <%= link_to drop_course_student_path(student_id: @student.id, course_id: course.id), method: :delete, data: { confirm: 'Are you sure you want to drop this course?' } do %>
        <button class="btn btn-outline-primary dropButton"><i class="fas fa-minus-circle"></i> Drop course</button>
        <% end %>
        </div>
    </div>
</div>

<script>

    
</script>

app/views/students/_edit_form.html.erb
<div class="row" id="signup-row" >
<div id="signup-form-content">
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(student.errors.count, "error") %> prohibited this professor from being saved:</p>
      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :email, class:'signup-label' %>
  <%= form.email_field :email, class: 'form-control signup-input'%>
  
  <%= form.label :First_name , class:'signup-label' %>
  <%= form.text_field :firstname, class: 'form-control signup-input'%>
  
  <%= form.label :Last_name , class:'signup-label'%>
  <%= form.text_field :lastname, class: 'form-control signup-input'%>
  
  <%= form.label :password, class:'signup-label' %>
  <%= form.password_field :password, class: 'form-control signup-input' %>
  <%= form.label :password_confirmation, "Confirmation" , class:'signup-label'%>
  <%= form.password_field :password_confirmation, class: 'form-control signup-input'%>
  <br>
  <%= form.submit "Update Account", class: "btn btn-outline-primary", id:"signup-Button" %>

<% end %>
</div>
</div>

app/views/students/_form.html.erb
<h1 id="signup-title">New Account</h1>
<div class="row" id="signup-row">
<div id="signup-form-content">
    <%= form_with(model: student, local: true) do |form| %>
      <% if student.errors.any? %>
        <div id="error_explanation">
          <p><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</p>
          <ul>
            <% student.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.label :First_name , class:'signup-label'%>
      <%= form.text_field :firstname, class: 'form-control signup-input'%>
      
      <%= form.label :Last_name , class:'signup-label'%>
      <%= form.text_field :lastname, class: 'form-control signup-input' %>

      <%= form.label :email, class:'signup-label' %>
      <%= form.email_field :email, class: 'form-control signup-input'%>
      
      <%= form.label :password, class:'signup-label' %>
      <%= form.password_field :password, class: 'form-control signup-input' %>
      <%= form.label :password_confirmation, "Confirmation" , class:'signup-label'%>
      <%= form.password_field :password_confirmation, class: 'form-control signup-input' %>
      <br>
      <%= form.submit "Create Student Account", class: "btn btn-outline-primary", id:"signup-Button"%>
    <%end%>
  </div>
</div>

app/views/students/add_course.html.erb
<div class ='container' style="margin-top: 120px">
 <h2 style="text-align: center">Enter the course's PIN:</h2>
    <% search_course_path = @student.id.to_s+ "/search_course" %>
    <%= render 'add_form', search_course_student_path: search_course_path%>
    <br><br>
</div>

app/views/students/add_course.js.erb
$('#add-course-button a').hide().parent().append("<%= j render 'add_form', search_course_student_path: @student.id.to_s+"/search_course" %>");

app/views/students/edit.html.erb
<div class='view3'>
    <div class='container' id='signup-container'>
            <div class='signup-form'>
                <h1 id="signup-title">Editing Account</h1>
                <%= render 'edit_form', student: @student %>
        </div>
        
    </div> 
</div>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>
<div class='container' id='body-container-students-index'>
  
  <h1>Students</h1>
  
  <table>
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.firstname %></td>
          <td><%= student.lastname %></td>
          <td><%= student.email %></td>
          <!--
          <td><%= link_to 'Show', student %></td>
          <td><%= link_to 'Edit', edit_student_path(student) %></td>
          <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          -->
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <!--<%= link_to 'New Student', new_student_path %>-->
</div>

app/views/students/new.html.erb
<div class='view3'>
    <div class='container' id='signup-container' >
            <div class= 'signup-form'>
                <%= render 'form', student: @student %>
                <%= link_to 'Back to Home', root_path , id:"signup-back-path"%>
            </div>
        </div>
        
    </div> 
</div>

app/views/students/show.html.erb
<body class='view4'>
  <div class='container profile-container'>
    <% if notice%>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>
      <div class='row profile-row'>
        <div class='col profile-column'>
          <div class='row'>
            <div class='column'>
              <span class="fa-stack fa-3x">
                <i class="fas fa-circle fa-stack-2x" id="profile-icon"></i>
                <i class="fas fa-user-graduate fa-stack-1x fa-inverse"></i>
              </span>
            </div>
            <div class='column'>
              <p class='profile-name'><%= @student.firstname%> <%=@student.lastname %></p>
              <p class='profile-email'><%= @student.email %></p>
              <%= link_to 'Edit Account', edit_student_path(@student) %>
            </div>
          </div>
        </div>
        <div class='col profile-button-column'>
          <% add_course_path = @student.id.to_s+ "/add_course" %>
          <div id="add-course-button">
            <%= link_to add_course_path, remote: true do %>
              <button class="btn btn-outline-primary addButton"><i class="fas fa-plus"></i> Add new course</button>
            <% end %>
          </div>
        </div>
      </div>

      <hr/>
      <div class = "courses-info-row" id="students-course-info-row">
        <%= render partial: 'course', collection: @courses%>
      </div>

      <div>
      </div>
  </div>
</body>

<script>

</script>