config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'student_login', to: 'sessions#new_student'
  get 'professor_login', to: 'sessions#new_professor'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'

  resources :holdprojects

  resources :takings

  resources :courses do 
    member do
      post 'create_groups'
      patch 'toggle_voting'
    end
  end
  
  resources :professors

  resources :students do
    member do
      get 'add_course'
      post 'search_course'
      delete 'drop_course'
    end
  end


  resources :professors do
    member do
      get 'add_course'
      post 'create_course'
    end
  end

  resources :account_activations, only: [:edit]

  resources :preferences 

  resources :groups do
    member do
      patch :move
      patch :vote
    end 
  end 


  root 'pages#home'
end

app/models/group.rb
class Group < ApplicationRecord
    acts_as_list scope: :course
    has_many :takings
    has_many :students, through: :takings
    belongs_to :course
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :move, :vote]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @students = @group.students
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        course = Course.find(params[:group][:course_id].to_i)
        @room = Course.find_by(params[:course_id])
        RoomChannel.broadcast_to @room, {commit: 'addCard', payload: render_to_string(:show, formats: [:json])}
        format.html { redirect_to course, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

 

  
  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def move
    @group.update(group_params)
    @room = Course.find_by(params[:course_id])
    RoomChannel.broadcast_to @room, { commit: 'moveCard', payload: render_to_string(:show, formats: [:json]) }
    render action: :show
  end

  def vote
    @group.update(group_params)
    @room = Course.find_by(params[:course_id])
    RoomChannel.broadcast_to @room, { commit: 'vote', payload: render_to_string(:show, formats: [:json]) }
    render action: :show
  end 
  

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { render :show}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:course_id, :project_name, :description, :position, :vfirst, :vsecond, :vthird, :active)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @course.nil?%>
    <div class="field">
      <%= form.number_field :course_id, class: "form-control textarea editbox-stu" %>
    </div>
  <% else %>
    <div class="field">
      <%= form.hidden_field :course_id, :value => @course.id %>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :project_name, class: "form-control textarea editbox-stu", placeholder: "Project name"%>
  </div>

  <div class="field">
    <%= form.text_field :description, class: "form-control textarea editbox-stu", placeholder: "Description"%>
  </div>

  <div class="actions">
    <%= form.submit  "Add New Project", class: "btn btn-outline-primary addProjectBtn-stu"%>
  </div>
<% end %>

app/views/groups/create.js.erb
$('#student-projects-container').append("<%= j render 'courses/group', group: @group %>");

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>
<%if current_user_type == "professor" ||current_user_type == "student"then%>
<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Project name</th>
      <th>Description</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <% if group.hold== false then%>
      <tr>
        <td><%= group.course_id %></td>
        <td><%= group.project_name %></td>
        <td><%= group.description %></td>
        <!--<td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
      <%end%>
    <% end %>
  </tbody>
</table>
<%else%>
      <p style="font-size:160%;">This information is hidden from visitors </p>
<%end%>
<br>

<!--<%= link_to 'New Group', new_group_path %>-->

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group, course: params[:course]%>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @group.course_id %>
</p>

<p>
  <strong>Project name:</strong>
  <%= @group.project_name %>
</p>  
<p>
  <% description = @group.description %>
</p>
<% vfirst = @group.vfirst %>
<% vsecond = @group.vsecond%>
<% vthird = @group.vthird%>

<p>

</p>



<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>