config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'student_login', to: 'sessions#new_student'
  get 'professor_login', to: 'sessions#new_professor'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'

  resources :holdprojects

  resources :takings

  resources :courses do 
    member do
      post 'create_groups'
      patch 'toggle_voting'
    end
  end
  
  resources :professors

  resources :students do
    member do
      get 'add_course'
      post 'search_course'
      delete 'drop_course'
    end
  end


  resources :professors do
    member do
      get 'add_course'
      post 'create_course'
    end
  end

  resources :account_activations, only: [:edit]

  resources :preferences 

  resources :groups do
    member do
      patch :move
      patch :vote
    end 
  end 


  root 'pages#home'
end

app/models/professor.rb
class Professor < ApplicationRecord
    attr_accessor :activation_token
    has_many :courses
    has_secure_password

    before_save { self.email = email.downcase }
    before_create :create_activation_digest

    validates :firstname,  presence: true, length: { maximum: 50 }
    validates :lastname,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, 
            format: { with: VALID_EMAIL_REGEX }, 
            uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    validates :email, uniqueness: true

    def full_name
        "#{firstname + " " + lastname}"
    end
    
    def Professor.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Activates an account.
    def activate
        update_attribute(:activated, true)
    end

    # Sends activation email.
    def send_activation_email
        UserMailer.account_activation(self).deliver_now
    end

    # Returns a random token.
    def Professor.new_token
        SecureRandom.urlsafe_base64
    end

    def authenticated?(attribute, token)
        digest = send("#{attribute}_digest")
        return false if digest.nil?
        BCrypt::Password.new(digest).is_password?(token)
    end

    private

        # Creates and assigns the activation token and digest.
        def create_activation_digest
            self.activation_token  = Professor.new_token
            self.activation_digest = Professor.digest(activation_token)
        end
    
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
    @courses = @professor.courses
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)
    respond_to do |format|
      @professor.activated = true
      if @professor.save
        # @professor.activated = true
        log_in(@professor, "professor")
        
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  #GET /professors/1/add_course
  def add_course
    @professor = Professor.find(params[:id])
    @professor_id = params[:id]
  end

  #POST /professors/1/create_course
  def create_course
    @course = Course.create(name: params[:name], pin: params[:pin], professor_id: params[:professor_id])
    redirect_to :controller => 'professors', :action => 'show', :id => params[:id]
  end





  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /professors/createPreference
  def createPreference
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:firstname, :lastname, :email, :password, :password_confirmation)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_add_form.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">

        <%= form_with(url: create_course_professor_path, method: "post") do |form| %>
            
            <%= form.text_field :name, placeholder: "Enter Course Name" , style:"width:260px; margin-bottom: 5px"%>
        
            <%= form.number_field :pin, placeholder: "Enter Course Pin", style:"width: 260px"%>
        
            <%= form.hidden_field :professor_id, :value => current_user.id%>

            <%= submit_tag("Add", class: "add-course-button-p") %>
            
        <% end %>

    </div>
</div>

app/views/professors/_course.html.erb
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

<div class="container course-column-box-professor">
    <div class='row course-name-row' >
        <div id="course-name"><%= link_to course.name, course, class:'btn course-name-button' %></div>
    </div>
    
    
    <% if course.students.size==0 %>  
        <div class='not-assigned-text-professor'>
            <h6>No Student Enrolled</h6>
        </div>
    <% elsif  findGroup(course.students[0], course).nil?%>
        <div class='not-assigned-text-professor'>
            <h6>No Groups Created Yet</h6>
        </div>        
    <% else %>
        
        <div class='assigned-text-professor'>
            <img src="/assets/green_check.jpg" height="22" width="22"> 
            <body>&nbsp;&nbsp;Group Created</body>
        </div>    
    <% end %>
    <div class='row course-drop-row'>
        <div id="course-drop-button">
        <%= link_to course, method: :delete, data: { confirm: 'Are you sure you want to drop this course?' } do %>
        <button class="btn btn-outline-primary dropButton"><i class="fas fa-minus-circle"></i> Delete course</button>
        <% end %>
        </div>
    </div>
</div>

app/views/professors/_edit_form.html.erb
<div class="row" id="signup-row" >
<div id="signup-form-content">
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</p>
      <ul>
        <% professor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :email, class:'signup-label' %>
  <%= form.email_field :email, class: 'form-control signup-input'%>
  
  <%= form.label :First_name , class:'signup-label' %>
  <%= form.text_field :firstname, class: 'form-control signup-input'%>
  
  <%= form.label :Last_name , class:'signup-label'%>
  <%= form.text_field :lastname, class: 'form-control signup-input'%>
  
  <%= form.label :password, class:'signup-label' %>
  <%= form.password_field :password, class: 'form-control signup-input' %>
  <%= form.label :password_confirmation, "Confirmation" , class:'signup-label'%>
  <%= form.password_field :password_confirmation, class: 'form-control signup-input'%>
  <br>
  <%= form.submit "Update Account", class: "btn btn-outline-primary", id:"signup-Button" %>

<% end %>
</div>
</div>

app/views/professors/_form.html.erb
<h1 id="signup-title">New Account</h1>
<div class="row" id="signup-row" >
<div id="signup-form-content">
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</p>
      <ul>
        <% professor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.label :First_name , class:'signup-label' %>
  <%= form.text_field :firstname, class: 'form-control signup-input'%>
  
  <%= form.label :Last_name , class:'signup-label'%>
  <%= form.text_field :lastname, class: 'form-control signup-input'%>

  <%= form.label :email, class:'signup-label' %>
  <%= form.email_field :email, class: 'form-control signup-input'%>
  
  <%= form.label :password, class:'signup-label' %>
  <%= form.password_field :password, class: 'form-control signup-input' %>
  <%= form.label :password_confirmation, "Confirmation" , class:'signup-label'%>
  <%= form.password_field :password_confirmation, class: 'form-control signup-input'%>
  <br>
  <%= form.submit "Create Professor Account", class: "btn btn-outline-primary", id:"signup-Button" %>

<% end %>
</div>
</div>

app/views/professors/add_course.html.erb
<% create_course_path = @professor.id.to_s+ "/create_course" %>
<%= render 'add_form' , create_course_professor_path: create_course_path%>

app/views/professors/add_course.js.erb
$('#add-course-button-p a').hide().parent().append("<%= j render 'add_form', create_course_professor_path: @professor.id.to_s+"/create_course" %> ");

app/views/professors/edit.html.erb
<div class='view3'>
    <div class='container' id='signup-container'>
            <div class='signup-form'>
                <h1 id="signup-title">Editing Account</h1>
                <%= render 'edit_form', professor: @professor %>
        </div>
        
    </div> 
</div>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.firstname %></td>
        <td><%= professor.lastname %></td>
        <td><%= professor.email %></td>
        <!--
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Professor', new_professor_path %>-->

app/views/professors/new.html.erb
<div class='view3'>
    <div class='container' id='signup-container'>
            <div class='signup-form'>
                <%= render 'form', professor: @professor %>
            </div>
        </div>
        
    </div> 
</div>

app/views/professors/show.html.erb
<body class='view4'>
  <div class='container profile-container'>
    
    <% if notice%>
      <div class="alert alert-success">
        <%= notice %>
      </div>
    <% end %>

    <% if flash[:success]%>
      <div class="alert alert-success">
        <%= flash[:success] %>
      </div>
    <% end %>
    
     
      <div class='row profile-row'>
        <div class='col profile-column'>
          <div class='row'>
            <div class='column'>
              <span class="fa-stack fa-3x">
                <i class="fas fa-circle fa-stack-2x" id="profile-icon"></i>
                <i class="fas fa-chalkboard-teacher fa-stack-1x fa-inverse"></i>
              </span>
            </div>
            <div class='column'>
              <p class='profile-name'><%= @professor.firstname%> <%=@professor.lastname %></p>
              <p class='profile-email'><%= @professor.email %></p>
              <%= link_to 'Edit Account', edit_professor_path(@professor) %>
            </div>
          </div>
        </div>
        <div class='col profile-button-column' >
          <% add_course_path = @professor.id.to_s+ "/add_course" %>
          <div id="add-course-button-p">
            <%= link_to add_course_path, remote: true do %>
              <button class="btn btn-outline-primary addButton"><i class="fas fa-plus"></i> Add new course</button>
            <% end %>
          </div>

          
        </div>
      </div>

      <hr/>
      <div class = "courses-info-row" id="professor-course-info-row">
        <%= render partial: 'course', collection: @courses%>
      </div>


  </div>
</body>

<script>

</script>