config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'student_login', to: 'sessions#new_student'
  get 'professor_login', to: 'sessions#new_professor'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'

  resources :holdprojects

  resources :takings

  resources :courses do 
    member do
      post 'create_groups'
      patch 'toggle_voting'
    end
  end
  
  resources :professors

  resources :students do
    member do
      get 'add_course'
      post 'search_course'
      delete 'drop_course'
    end
  end


  resources :professors do
    member do
      get 'add_course'
      post 'create_course'
    end
  end

  resources :account_activations, only: [:edit]

  resources :preferences 

  resources :groups do
    member do
      patch :move
      patch :vote
    end 
  end 


  root 'pages#home'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :toggle_voting, :destroy]
  include CoursesHelper
  
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    if params[:teams].nil?
      @teams = {}
    else
      @teams = params[:teams]
    end
    
    @preferences = @course.preferences
    @groups = @course.groups
  end


  #PATCH /courses/1/toggle_voting
  def toggle_voting
    puts "in toggle voting"
    respond_to do |format|
      if @course.update(course_params)        
        @room = Course.find_by(params[:course_id])
        puts "Broadcasting to #{@room.id.to_s}"
        RoomChannel.broadcast_to @room, { commit: 'toggleVoting', payload: render_to_string(:show, formats: [:json]) }
        format.json { render :show, status: :ok, location: @course }
    
      else
        puts "\n\n\n ******** course not saved *************\n\n\n"
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end


  #POST /courses/1/create_groups
  def create_groups
    group_service = GroupCreationManager::GroupMatcher.new #contains group creation functions
    error_service = GroupCreationManager::MatchingErrorGenerator.new # Contains error detection and generation functions
    @course = Course.find(params[:id])
    algorithm = params[:algo]
    errors = error_service.handle_group_creation_errors(@course, algorithm)
    if errors.size > 0
      flash[:alert] = error_service.to_message_array(errors)
      redirect_to @course and return
    end
    group_service.determineAlgorithmAndMatch(@course, params)
    flash[:success] = "Groups created!"
    redirect_to @course
  end

  # GET /courses/new
  def new
    @course = Course.new
    #@user_id = current_user.id
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.js
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    professor = @course.professor 
    @course.destroy
    respond_to do |format|
      format.html { redirect_to professor, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :pin, :professor_id, :voting)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper

    def showStudents(students)
        student_string = ""
        students.each do |student|
            student_string += student.firstname + " " + student.lastname + ", "
        end
        return student_string
    end

    def showGroups(groups)
        group_hash = {}
        groups.each do |group|
          group_string = ""
          group.students.each do |student|
            group_string += student.firstname + " " + student.lastname + ", "
          end
          group_hash[group.project_name] = group_string
        end
        return group_hash
    end

    def get_professor_id(course)
      professor = course.professor
      if !professor.nil?
        professor_id = professor.id
      else
        professor_id = nil
      end
      return professor_id
    end

    def three_active_groups?(course)
      active_groups = 0
      @groups.each do |group|
        if group.active
          active_groups += 1
        end
      end

      if active_groups < 3
        return false
      end

      return true
    end

    def button_disabled?(course)
      return !three_active_groups?(course) || course.voting
    end

    def get_message(course)
      if three_active_groups?(course)
        return ""
      end
      return "Less than 3 active projects"
    end

end

app/views/courses/_form.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">

        <%= form_with(model: course) do |form| %>
            <% if course.errors.any? %>
                <div id="error_explanation">
                    <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

                    <ul>
                         <% course.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                    <% end %>
                    </ul>
                </div>
            <% end %>

            
            <%= form.text_field :name, placeholder: "Enter Course Name" , style:"width:260px; margin-bottom: 5px"%>
        
            <%= form.number_field :pin, placeholder: "Enter Course Pin", style:"width: 260px"%>
        
            <%= form.hidden_field :professor_id, :value => current_user.id%>

            <%= submit_tag("Add", class: "add-course-button-p") %>
            
        <% end %>

    </div>
</div>

app/views/courses/_group.html.erb
<a class = 'single-project-container-stu' >
    <div class='project-name'>
        <p >
            <%= group.project_name %>
        </p>
    </div>
    <div class='project-description'>
        <p><%= group.description%></p>
    </div>
</a>

app/views/courses/_groups.html.erb
<div class = "row" id="course-group-info-row" >
<% if @course.students.size==0 %>
    <h6>No Student Enrolled</h6>
<% elsif findGroup(@course.students[0], @course).nil? %>
    <h6>No Groups Created Yet</h6>
<% else %>
    <% @course.groups.where(active: true).each do |group| %>
        <div class="container course-group-box">
            <p> <%= group.project_name %> </p>                  
            <div>
                <% group_members = group.students%>
                <div class = "wrapper overflow course-group-container">
                    <table class = "table table-hover table-sm">
                        <thead>
                            <tr>
                                <th style='border-top: 0'>Name</th>
                                <th style='border-top: 0'>Email</th>
                                        
                            </tr>
                        </thead>
                        <tbody>
                            <% group_members.each do |stu| %>
                            <tr>
                                <td><%= stu.firstname + " " + stu.lastname%>
                                <td><%= stu.email%>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    <%end%>
<%end%>
</div>

app/views/courses/_professor-preference.html.erb
            <div class="modal fade" id="professor-preference-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content" style="padding-left: 30px">
                  <div class="modal-header border-bottom-0">
                    <h5 class="modal-title" id="exampleModalLabel">Create Your Preference for: <span style="color:rgb(77, 131, 203)"><%= @course.name %></span></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                
                  <div class="modal-body">
                      <%= form_with(url: create_groups_course_path, local: true) do |f| %>
                        <%= hidden_field_tag :algo, 'holistic'%>
                        <div class="alert alert-danger d-none">Please review the problems below:</div>
                       
                        <label style="margin-right: 35px;font-size:22px;"><%= f.label 'How important are students\' preferences on project choices?'%> </label>
                        <%= f.collection_radio_buttons :projectWeight, [[1,1],[2,2],[3,3],[4,4],[5,5]], :first, :last, { item_wrapper_tag: false },{:style=>"
                        margin-left: 24px; margin-right:5px;"}%>
                        very important<br>
                        <hr size="10">
                        <label style="margin-right: 3px;font-size:22px;"><%= f.label 'Do you want each team to have various levels of coding proficiencies?' %></label>
                        <%= f.collection_radio_buttons :codingWeight, [[1,1],[2,2],[3,3],[4,4],[5,5]], :first, :last, { item_wrapper_tag: false },{:style=>"
                        margin-left: 24px; margin-right:5px"}%>
                        As diverse as possible<br><hr size="10">
                        <label style="margin-right: 33px;font-size:22px;"><%= f.label 'How important are students\' preferences on their partner choice?'%></label>
                        <%= f.collection_radio_buttons :partnerWeight, [[1,1],[2,2],[3,3],[4,4],[5,5]], :first, :last, { item_wrapper_tag: false },{:style=>"
                        margin-left: 24px; margin-right:5px"}%>
                        very important<br><hr size="10">
                        <label style="margin-right: 68px;font-size:22px;"><%= f.label 'Should team members have more than 2 hours/week avaiable meeting-time?'%></label>
                        <%= f.collection_radio_buttons :scheduleWeight, [[1,1],[2,2],[3,3],[4,4],[5,5]], :first, :last, { item_wrapper_tag: false },{:style=>"
                        margin-left: 24px; margin-right:5px"}%> very important
                        <div class="modal-footer border-top-0 d-flex justify-content-center">
                          <div style="margin-left: 80px; margin-bottom: 50px ">
                            <%= f.submit("Submit and Create Group", class: "btn btn-outline-primary addButton") %>
                            <button class="btn btn-primary resetButton" type="reset">Reset</button>
                          </div>
                        </div>
                      <%end%>
                  </div>
                </div>
              </div>
            </div>

app/views/courses/_students.html.erb
<% group_members = @course.students%>
<div class = "wrapper overflow students-container">
    <table class = "table table-hover table-sm" id="students-table">
        <thead>
            <tr>
                <th style='border-top: 0'>Name</th>
                <th style='border-top: 0'>Email</th>
            </tr>
        </thead>
        <tbody>
            <% group_members.each do |stu| %>
            <tr>
                <td><%= stu.firstname + " " + stu.lastname%>
                <td><%= stu.email%>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/courses/create.js.erb
$('#add-course-button-p add_form').remove();
$('#add-course-button-p a').show();
$('#professor-course-info-row').append("<%= j render @course %>");

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<% if logged_in? %>
    <%= render 'form', course: @course %>
<% else %>
    <p> Please log in first <p>
<% end %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>
<%if current_user_type == "professor" || current_user_type == "student"then%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pin</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.pin %></td>
        
        <td align="center"><%= course.professor_id %></td>
        <!--
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
  

</table>
<%else %>
    <br>
    <p style="font-size:160%;"><strong>Please log in to see further information</strong></p>
  <%end %>
<br>

<!--<%= link_to 'New Course', new_course_path %> -->

app/views/courses/show.html.erb
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>


<body class='view4'>
  <div class='container profile-container' id="classroom" data_channel_subscribe="room" data-room-active="<%= @course.has_enough_projects%>" data-room-id="<%= @course.id %>" data-room-voting="<%= @course.voting%>">
  
    <% if !flash[:alert].nil?%>
      <div class="alert alert-danger">
        <strong> Group creation had the following errors: </strong>
        <% flash[:alert].each do |error| %>
          <li> <%= error %> </li>
        <% end %>
      </div>
    <% end %>

    <% if !flash[:success].nil?%>
      <div class="alert alert-success">
        <%= flash[:success] %>
      </div>
    <%end %>


    <% if @course.errors.any? %>
      <div class="alert alert-danger">
        <p><%= pluralize(@course.errors.count, "error") %> prohibited this course from being updating:</p>
        <ul>
          <% @course.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %> 
      <div class='row profile-row'>
        <div class='col course-profile-column'>
          <p class="course-title">
            <strong><%= @course.name %></strong>
          </p>

          <p class="secondary-title">
            <strong>Pin:</strong>
            <%= @course.pin %>
          </p>

          <p class="secondary-title">
            <strong>Professor:</strong>
            <% professor = @course.professor %>
            <%= professor.firstname + ' '+ professor.lastname  %>
          </p>
        </div>

        <% if current_user_type == "professor" && get_professor_id(@course) == current_user.id%>
          <% create_groups_path = @course.id.to_s+ "/create_groups" %>
          <div class='col course-button-column'>
            <%= button_to 'Create Random Groups', {:controller => "courses", :action => "create_groups", :algo => "random"}, :class => "btn btn-outline-primary addButton", :method=>:post%>
            <br>
            
            <div id='header' class="header">
            <div>
              <p class="warning"> <strong> Group Creation using preferences is disabled due to: </strong> </p>
            </div>
            
            
              
              <div id="active3-warning-show">
                <img id="active3-img" src="/assets/yellow-alert.png" height="22" width="22">
                <p class="warning" id="warning-message"> Less than 3 active projects </p>
              </div>
              
              <div id="active3-warning-hide"></div>
              

              <div class="warnings">
                <img src="/assets/yellow-alert.png" height="22" width="22">
                <p class="warning">  Voting still in progress </p>
              </div>
              <p></p>
            </div>
            

            <div class = disabled>
              <%= button_to 'Create Groups Based on Project Preference', {:controller => "courses", :action => "create_groups", :algo => "project_only"},  :disabled => true, :class => "btn btn-outline-primary addButton", :method=>:post%>
              <br>
              <button disabled class="btn btn-outline-primary addButton" data-toggle="modal" data-target="#professor-preference-form">
                Create Groups Based on All Preference
              </button>
            </div>

            <div class = enabled >
              <%= button_to 'Create Groups Based on Project Preference', {:controller => "courses", :action => "create_groups", :algo => "project_only"},  :disabled => false, :class => "btn btn-outline-primary addButton", :method=>:post%>
              <br>        
              <button class="btn btn-outline-primary addButton" data-toggle="modal" data-target="#professor-preference-form">
                Create Groups Based on All Preference
              </button>
            </div>
              
          </div>

            <div class="modal fade" id="professor-preference-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header border-bottom-0">
                    <h5 class="modal-title" id="exampleModalLabel">Create Your Preference for: <span><%= @course.name %></span></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                
                  <div class="modal-body">
                      <%= form_with(url: create_groups_course_path, local: true) do |f| %>
                        <%= hidden_field_tag :algo, 'holistic'%>
                        <div class="alert alert-danger d-none">Please review the problems below:</div>
                       
                        <label class="modal-label"><%= f.label 'How important are students\' preferences on project choices?'%> </label>
                        <%= f.collection_radio_buttons :projectWeight, [[1,1],[2,2],[3,3],[4,4],[5,5]], :first, :last, { item_wrapper_tag: false },{:style=>"
                        margin-left: 24px; margin-right:5px;"}%>
                        <br> <p> unimportant &emsp; &emsp; &emsp; &emsp; &emsp; very important </p>
                        <hr size="10">
                        <label class="modal-label"><%= f.label 'Do you want each team to have various level of coding proficiencies?' %></label>
                        <%= f.collection_radio_buttons :codingWeight, [[1,1],[2,2],[3,3],[4,4],[5,5]], :first, :last, { item_wrapper_tag: false },{:style=>"
                        margin-left: 24px; margin-right:5px"}%>
                        <p> not diverse &emsp; &emsp; &emsp; &emsp; &emsp; as diverse as possible </p><hr size="10">
                        <label class="modal-label"><%= f.label 'How important are students\' preferences on their partner choice?'%></label>
                        <%= f.collection_radio_buttons :partnerWeight, [[1,1],[2,2],[3,3],[4,4],[5,5]], :first, :last, { item_wrapper_tag: false },{:style=>"
                        margin-left: 24px; margin-right:5px"}%>
                        <p> unimportant &emsp; &emsp; &emsp; &emsp; &emsp; very important </p><hr size="10">
                        <label class="modal-label"><%= f.label 'Should team members have more than 2 hours/week avaiable meeting-time?'%></label>
                        <%= f.collection_radio_buttons :scheduleWeight, [[1,1],[2,2],[3,3],[4,4],[5,5]], :first, :last, { item_wrapper_tag: false },{:style=>"
                        margin-left: 24px; margin-right:5px"}%> <p> unimportant &emsp; &emsp; &emsp; &emsp; &emsp; very important </p>
                        <div class="modal-footer border-top-0 d-flex justify-content-center">
                          <div class='modal-button'>
                            <%= f.submit("Submit and Create Group", class: "btn btn-primary createButton") %>
                            <button class="btn btn-outline-primary addButton" type="reset">Reset</button>
                          </div>
                        </div>
                      <%end%>
                  </div>
                </div>
              </div>
            </div>


        <% elsif current_user_type == "student" %>
          <div class='col course-button-column-stu'>
            
            <div id="create-preference-show">
              <%if !Preference.find_by(student_id:current_user.id, course_id:@course.id).nil?%>
                <img src="/assets/green_check.jpg" height="22" width="22">
                <p class ="warning"> Your preference has been recorded</p>
                <p></p>
              <%end%>

              <%= link_to new_preference_path(course: @course) do %>
                <button class="btn btn-outline-primary addButton btn-lg"></i> Create Preference</button>
              <% end %>
            </div>
           
            <div id="create-preference-hide">
              <img src="/assets/yellow-alert.png" height="32" width="32"> 
              <p class ="warning"> Can not create preferences until voting has ended </p>
              <br> <br>
            </div>
            
          </div>
        <% end %>
      </div>

      <hr/>
      
      <div class='row' id='course-info-box'>
        <div class='col' id='course-info-col'>
          <ul class="nav nav-tabs" id="course-nav">
            <li class="nav-item">
              <a href="#projects" class="nav-link tab-projects active" data-toggle="tab" >Projects</a>
            </li>
            <li class="nav-item">
              <a href="#students" class="nav-link tab-students" data-toggle="tab" >Students</a>
            </li>
            
            <li class="nav-item">
              <a href="#groups" class="nav-link tab-groups" data-toggle="tab" >Groups</a>
            </li>
          </ul>

          <div class="tab-content">

            <div class="tab-pane fade show active" id="projects">
              <% if current_user_type == "professor" && get_professor_id(@course) == current_user.id%>
                <br>
                <div id = "toggle-container">
                  <% if @course.voting==true %>
                  <p class="status" id="status">Current Process: Voting</p>
                  <button class="btn btn-primary btn-lg" id="toggle-button" data-turbolinks="false"> End Voting and Allow Preferences</button>
                  <%else%>
                  <p class="status" id="status">Current Process: Preference Filling</p>
                  <button class="btn btn-primary btn-lg" id="toggle-button" data-turbolinks="false"> Resume Voting</button>
                  <%end%>

                </div>
                <%= tag.div id: :boards, data:{groups: @course.groups.to_json, course: @course.to_json}%>
              <% else %>    
                <%= tag.div id: :stuboards, data:{groups: @course.groups.to_json,course:@course.to_json, student: Student.find(current_user.id).to_json, taking: Taking.find_by(student_id:current_user.id, course_id:@course.id).to_json}%>              
              <%end%>
            </div>

            <div class="tab-pane fade " id="students">
              <div class="container projects-box">
                <%= render 'students' %>
              </div>
            </div>

            <div class="tab-pane fade" id="groups">
              <div class="container projects-box">   
                <%= render 'groups' %>
              </div>
            </div>
         
          </div> 
        </div>
              
      </div>

  </div>
</body>

<script>



</script>